feat: deploy mock contracts #100 and  feat: approve scripts to aid swaps #99
blockful-io/swaplace-contracts pull request #108
Opened 2023-11-23 21:29 UTC by blackbeard002

mock.ts script to deploy and mint ERC20 and ERC721. 

- Deploy the mocks contracts
- Minting of tokens
- Approvals of tokens  #99 [ ](url)

2023-12-04 11:57 UTC, 0xneves requested changes
Hey @blackbeard002 I was reviewing your PR, and I couldn't find the approval scripts referred on the #99, only the deploy script was committed, could you check that, please?

And the indentation of the code you committed is very different than the standard we are using. We are currently using prettier in its standard config, which is set automatically when you add it:

```
{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": false,
  "singleQuote": true
}
```

2023-12-04 11:57 UTC, 0xneves commented on scripts/mockERC.ts
The file needs to be formatted following the protocol standard.

2023-12-05 18:44 UTC, blackbeard002 commented
Hey @0xneves I'm sorry I didn't write a seperate script for approve. I assumed it had to be written in the deploy script itself since #99 was a part of #100. My bad, I'll look into it and do the necessary changes along with the indentation.

2023-12-06 19:33 UTC, blackbeard002 commented
yeah got the context now

2023-12-06 19:44 UTC, blackbeard002 commented
Hey @0xneves ready for review.

2023-12-07 05:43 UTC, 0xneves requested changes
Please help me fix these issues!

2023-12-08 16:23 UTC, blackbeard002 commented on scripts/approve.ts
Also about the single quote to double quotes changes, the prettier config standard you mentioned earlier has "singleQuote": true. So it was all switched to single quotes. should this value be removed or something from the prettier yml? For now I'm changing it to doubleQuote:true since you asked me to change single quotes to double quotes.

2023-12-14 16:07 UTC, 0xneves commented on scripts/approve.ts
> Hey @0xneves, Also about the single quote to double quotes changes, the prettier config standard you mentioned earlier has "singleQuote": true. So it was all switched to single quotes. should this value be removed or something from the prettier yml? For now I'm changing it to doubleQuote:true since you asked me to change single quotes to double quotes.

Hey @blackbeard002 
The mentioned issue was fixed in #128

2023-12-19 10:25 UTC, 0xneves commented
Hey @blackbeard002 Talked to you in discord, let's speed this up as it is review for almost a month now 🥵

2023-12-19 19:47 UTC, blackbeard002 commented
yeah I'm on it

2023-12-19 23:43 UTC, blackbeard002 commented
Hey @0xneves, ready for review. I've made changes according to the info and params mentioned here on this PR chat. Lemme know if any changes are needed.

2023-12-21 05:57 UTC, 0xneves approved these changes
Awesome @blackbeard002 !! 

I'm approving this PR

2023-12-21 05:57 UTC, merged