feat: [ISSUE-119] feat: adding a receiver as parameter in the accept swap function
blockful-io/swaplace-contracts pull request #149
Opened 2023-12-19 15:40 UTC by 0xjoaovpsantos

This PR close #119 

Proposal in the issue:

- [x] add an address type into the acceptSwap parameter with the name of receiver.
- [x] instead of sending the assets to the msg.sender, send it to the receiver instead.

Plus:

- I created a "approveToken.ts" script to help us to approve tokens to test the flow creating and accepting swaps, it's only a suggestion, I can remove it if you think it's not necessary :)

Tests:

- Contract deployed to test: https://sepolia.etherscan.io/address/0x156A2e49B89127A23a94c3B17C02d13315f06e19
- Swap accept events with the receiver address: https://sepolia.etherscan.io/address/0x156A2e49B89127A23a94c3B17C02d13315f06e19#events

Example transaction: https://sepolia.etherscan.io/tx/0xf9b626c70167d25319884791913857ce748eee1696cb8c35d932ae9ef267f193

- msg.sender send to owner of swap created
- owner of swap created send to receiver

2023-12-19 19:28 UTC, 0xjoaovpsantos commented
I'm fixing the conflicts

2023-12-19 19:39 UTC, 0xjoaovpsantos commented
Fixed all conflicts in the PR with main branch and errors in the unit tests  :)

2023-12-19 19:43 UTC, 0xjoaovpsantos commented
Okay, now it's ready to review rs

2023-12-19 19:48 UTC, 0xjoaovpsantos commented
@0xneves

2023-12-21 17:16 UTC, 0xjoaovpsantos commented
Fixed the PR conflicts :)

2023-12-22 20:54 UTC, 0xneves requested changes
Requesting for changings in the following files:

2023-12-22 20:54 UTC, 0xneves commented on scripts/approveToken.ts
This script is not part of the proposal and should not be committed

2023-12-22 20:54 UTC, 0xneves commented on test/utils/utils.ts
This addition is not part of the issue and should be added in this PR

2024-01-03 13:11 UTC, 0xneves commented
@0xjoaovpsantos Happy New Year, how is this task going? We just need minor changes to approve this!

2024-01-03 23:23 UTC, 0xjoaovpsantos commented
HEEEEEEEY @0xneves HAPPY NEW YEAR MANNN

Sorry for the delay, I fixed this detail :)

2024-01-16 16:52 UTC, 0xneves approved these changes

2024-01-16 16:52 UTC, merged