feature: handle errors
blockful-io/swaplace-contracts pull request #157
Opened 2023-12-20 09:47 UTC by luislucena16

done! I will create other issues to modify other things in relation to errors

2023-12-21 05:39 UTC, 0xneves requested changes
Minor fix in SwapFactory requested

2023-12-21 05:39 UTC, 0xneves commented on contracts/SwapFactory.sol
Duplicated lines in 58 and 61

2023-12-21 10:37 UTC, luislucena16 commented on contracts/SwapFactory.sol
fixed!

2023-12-22 20:35 UTC, 0xneves approved these changes

2023-12-22 20:35 UTC, merged