parseData() and packData() implemented #104
blockful-io/swaplace-contracts pull request #165
Opened 2023-12-22 23:24 UTC by blackbeard002

- [x] Changes in all the contracts for bitwise refactor done and compiled successfully.
 - [x] Fuzzing altered accordingly.  
- [ ] Unit tests yet to be re-written in hardhat. Not yet ready for review. 

closes #104

2023-12-28 17:22 UTC, blackbeard002 commented
@0xneves Hey, ready for review.

2024-01-15 21:20 UTC, 0xneves requested changes
Thank you a lot @blackbeard002 !! Just a few minor improvements and I will submit the PR, I think the hardest one its the NatSpec, since it need good communication xD 

LFG

2024-01-15 21:20 UTC, 0xneves commented on contracts/SwapFactory.sol
Could you provide a NatSpec description for this function explaining how it works?
Since the explanation should stay in the Interface contract, the implementation should be used the reference just like in the rest of the contract e.g.:

```
  /**
   * @dev See {ISwaplace-getSwap}.
   */
```

2024-01-15 21:20 UTC, 0xneves commented on contracts/Swaplace.sol
> +    expiry = 0;
This line is unnecessary as the `0` can be directly inputted in line 66 in the expiry variable of packData

2024-01-15 21:20 UTC, 0xneves commented on contracts/interfaces/ISwap.sol
The file was commited using tabWidth = 4, but the correct is tabWidth = 2.

The following should follow pattern and should be changed from:
```
     * - `config` holds two values 'allowed' and 'expiry',packed using bitwise.  
     *       'allowed' address to accept the Swap.
     *       'expiry' date of the Swap.
```
To:
```
     * - `config` represents two packed values: 'allowed' for the allowed address 
     * to accept the swap and 'expiry' for the expiration date of the swap.
```

2024-01-15 21:20 UTC, 0xneves commented on contracts/interfaces/ISwapFactory.sol
Could you provide a NatSpec description for this function explaining how it works

2024-01-15 21:20 UTC, 0xneves commented on test/TestSwapFactory.test.ts
Avoid using underscores to name variables in the test file, since there is a conflict, the best method would be to rename the variables that don't resemble the contracts, for instance:
- Change `_expiry` into `timestamp`
- Keep the config expiry as expiry, since its the same inside the contract implementation

2024-01-15 21:20 UTC, 0xneves commented on test/TestSwapFactory.test.ts
Changing the `expiry` into `configExpiry` is also a go, but the first recommendation suits more the legibility.

2024-01-15 21:20 UTC, 0xneves commented on test/TestSwaplace.test.ts
Same recommendation as the `TestSwapFactory.test.ts`

2024-01-16 13:52 UTC, blackbeard002 commented
Hey @0xneves I've made the changes that you requested. Ready for review.

2024-01-16 17:08 UTC, merged